//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by vmd.rc
//
#define IDC_LUCES_COLOR                 3
#define ID_PREFERENCIAS_RESET           3
#define IDD_ABOUTBOX                    100
#define IDD_ACERCA_DE                   100
#define IDD_VMD2_DIALOG                 102
#define IDD_V_MODELOS_DIALOG            104
#define IDD_MODELOS_DIALOG              104
#define IDD_V_ANIMACIONES_DIALOG        107
#define IDD_ANIMACIONES_DIALOG          107
#define IDD_LUCES_DIALOG                108
#define IDR_MAINFRAME                   128
#define IDR_VMDTYPE                     129
#define IDR_MENU_EMERGENTE              130
#define IDR_ACCELERATOR1                131
#define IDD_DIALOG_MODELOS              136
#define IDD_CAMARA_DIALOG               138
#define IDD_PREFERENCIAS_DIALOG         143
#define IDD_INFO_DIALOG                 144
#define IDD_LUCES_OPCIONES_DIALOG       145
#define IDD_DIALOG1                     146
#define IDC_B_CREDITOS                  1000
#define IDC_B_BORRAR_MODELO             1001
#define IDC_B_SALIR                     1002
#define IDC_D_BORRAR_ARMA               1002
#define IDC_B_INFO                      1003
#define IDC_B_MODELO                    1004
#define IDC_B_MODELOS                   1004
#define IDC_B_CAMARA                    1005
#define IDC_B_RESET                     1005
#define IDC_B_LUCES                     1006
#define IDC_B_OPCIONES                  1007
#define IDC_CAMBIO_FRAME                1007
#define IDC_CAJA_OBJETOS                1008
#define IDC_EDIT_FRAMES                 1008
#define IDC_ELEGIR_OBJETO               1009
#define IDC_B_SET_FRAME                 1009
#define IDC_B_ANIMACIONES               1010
#define IDC_CAJA_FRAME                  1010
#define IDC_CAJA_PLANO                  1011
#define IDC_B_RESET_ANIM                1011
#define IDC_CAJA_TRANSFORMACION         1012
#define IDC_CAJA_FPS                    1012
#define IDC_CAJA_LUCES                  1012
#define IDC_ELEGIR_PLANOS               1013
#define IDC_CAJA_LUCES_MOVER            1013
#define IDC_ELEGIR_TRANSFORMACION       1014
#define IDC_POS_LUZ_X                   1014
#define IDC_B_MODELOS_CERRAR            1015
#define IDC_POS_LUZ_Y                   1015
#define IDC_CAJA_BICHOS                 1016
#define IDC_POS_LUZ_Z                   1016
#define IDC_ELEGIR_MODELOS              1017
#define IDC_B_MODELO_TEXTURA            1019
#define IDC_LABEL_EJE_X                 1019
#define IDC_ELEGIR_ARMAS                1020
#define IDC_LABEL_EJE_Y                 1020
#define IDC_CAJA_MODELOS                1021
#define IDC_LABEL_EJE_Z                 1021
#define IDC_LABEL_EJE_X3                1021
#define IDC_ELEGIR_SOMBREADO            1022
#define IDC_SLIDER_AMBIENTE             1022
#define IDC_ETIQUETA_FPS                1023
#define IDC_ELEGIR_CAJAS                1023
#define IDC_SLIDER_DIFUSO               1023
#define IDC_SLIDER_ESPECULAR            1024
#define IDC_B_ARMA                      1025
#define IDC_SLIDER_BRILLOS              1025
#define IDC_B_ARMA_TEXTURA              1026
#define IDC_LUCES_ACTIVAS               1026
#define IDC_CAJA_ARMAS                  1027
#define IDC_CAJA_AMBIENTE               1027
#define IDC_B_COLOR                     1028
#define IDC_B_LUCES_CERRAR              1028
#define IDC_B_COLOR_CAJA                1029
#define IDC_L_FOV                       1029
#define IDC_CSTRIPS_FANS                1030
#define IDC_CAJA_CAMARA                 1030
#define IDC_CAJA_SOMBREADO              1031
#define IDC_EDIT_FOV                    1031
#define IDC_CAJA_CAJAS                  1032
#define IDC_B_ANIMACIONES_CERRAR        1032
#define IDC_EDIT_ASPECX                 1032
#define IDC_LUZ_EDIT_PX                 1032
#define IDC_SLIDER_INTER                1033
#define IDC_B_LUZ_APLICAR               1033
#define IDC_EDIT_ASPECY                 1033
#define IDC_LUZ_EDIT_PY                 1033
#define IDC_SLIDER_TIMER                1034
#define IDC_B_CAMARA_APLICAR            1034
#define IDC_CAJA_ANIMACIONES            1035
#define IDC_L_CAMARA_ASPECX             1035
#define IDC_ELEGIR_ANIMACION            1036
#define IDC_L_CAMARA_ASPECY             1036
#define IDC_B_ANIMACIONES_PLAY          1037
#define IDC_B_CAMARA_CERRAR             1037
#define IDC_CAJA_INTERPOLACION          1038
#define IDC_B_CAMARA_RESET              1038
#define IDC_CAJA_TIMER                  1039
#define IDC_CAJA_DIFUSO                 1039
#define IDC_CAJA_ESPECULAR              1040
#define IDC_CAJA_BRILLOS                1041
#define IDC_B_LUCES_RESET               1042
#define IDC_PREFERENCIAS_CAJA_VELOCIDAD_CAM 1043
#define IDC_B_LUCES_OPCIONES            1043
#define IDC_PREFERENCIAS_CAJA_VELOCIDAD_MD 1044
#define IDC_PREFECENCIAS_L_CAM_TRAS     1045
#define IDC_PREFERENCIAS_CAJA_VELOCIDAD_LUZ 1046
#define IDC_PREFERENCIAS_EDIT_VEL_CAM_TRAS 1047
#define IDC_PREFERENCIAS_EDIT_VEL_CAM_ROT 1048
#define IDC_ACERCA_DE_CAJA              1049
#define IDC_PREFERENCIAS_EDIT_VEL_TRAS_MOD 1049
#define IDC_ACERCA_DE_AUTORES           1050
#define IDC_PREFERENCIAS_EDIT_VEL_ROT_MOD 1050
#define IDC_ACERCA_DE_JOSE              1051
#define IDC_PREFERENCIAS_EDIT_VEL_TRAS_LUZ 1051
#define IDC_ACERCA_DE_JAVI              1052
#define IDC_PREFECENCIAS_L_CAM_TRAS_LUZ 1052
#define IDC_ACERCA_DE_IGA               1053
#define IDC_PREFECENCIAS_L_CAM_ROT      1054
#define IDC_PREFECENCIAS_L_MODELO_TRAS  1055
#define IDC_PREFERENCIAS_VELOCIDAD      1056
#define IDC_PREFECENCIAS_L_MODELO_ROT   1057
#define IDC_B_COLOR_FONDO               1058
#define IDC_INFO_CAJA_MODELOS           1059
#define IDC_INFO_CAJA_ARMA              1060
#define IDC_INFO_MODELO_FRAMES          1061
#define IDC_INFO_MODELO_VERTICES        1062
#define IDC_INFO_MODELO_CARAS           1063
#define IDC_LUZ_EDIT_PZ                 1063
#define IDC_INFO_MODELO_CT              1064
#define IDC_INFO_MODELO_GLC             1065
#define IDC_LUCES_MOSTRAR               1065
#define IDC_INFO_ARMA_FRAMES            1066
#define IDC_CAJA_LUZ_POS                1066
#define IDC_INFO_ARMA_VERTICES          1067
#define IDC_INFO_ARMA_CARAS             1068
#define IDC_INFO_ARMA_CT                1069
#define IDC_CREDITOS                    1069
#define IDC_INFO_ARMA_GLC               1070
#define ID_FILE_OPENE                   32771
#define ID_ANADIR_MODELO                32773
#define ID_ANADIR_ARMA                  32774
#define ID_VENTANA_MODELOS              32776
#define ID_VENTANA_ANIMACIONES          32777
#define ID_VENTANA_LUCES                32778
#define ID_VENTANA_CAMARA               32781
#define ID_OPCIONES_PREFERENCIAS        32782
#define ID_ARCHIVO_RESET                32785
#define ID_ARCHIVO_BORRAR_ARMA          32786
#define ID_ARCHIVO_BORRAR_MODELO        32787
#define ID_MENUEMERGENTE_MOVER          32788
#define ID_MENUEMERGENTE_ROTAR          32789
#define ID_MENUEMERGENTE_CAMARA         32792
#define ID_MENUEMERGENTE_LUCES          32793
#define ID_MENUEMERGENTE_XY             32794
#define ID_MENUEMERGENTE_MODELO         32796
#define ID_MENUEMERGENTE_XZ             32797
#define ID_MENUEMERGENTE_ZY             32799
#define ID_ARCHIVO_TEXTURA_MODELO       32801
#define ID_ARCHIVO_TEXTURA_ARMA         32803
#define ID_MENUEMERGENTE_LUZ            32804
#define ID_CAMBIAR_MOD_DER              32807
#define ID_CAMBIAR_MOD_IZQ              32808

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32809
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
